language: scala

scala:
  - 2.12.2

jdk:
  - oraclejdk8

sudo: false

script:
  - sbt clean coverage test coverageReport coverageAggregate codacyCoverage

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
